# Copyright (c) 2012, Braiden Kindt.
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 
#   1. Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
# 
#   2. Redistributions in binary form must reproduce the above
#      copyright notice, this list of conditions and the following
#      disclaimer in the documentation and/or other materials
#      provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
# ''AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
# WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.


import logging
import dbm
import os

_log = logging.getLogger("antagent.plugin")
_plugins = []

class Plugin(object):
    """
    A plugin receives notifications when new data
    is availible, it can consume the data or transform it.
    TCX file generation, and garmin connect upload are
    both implementations of plugin. You can implement
    your own to produce new file formats or upload somewhere.
    """

    def data_availible(self, device_sn, format, files):
        """
        Notification that data is availible, this could
        be raw packet data from device, or higher level
        data generated by other plugins, e.g. TCX.
        """
        pass

    def registered(self):
        """
        Callback when this plugin as been successfully
        registered with data notifier.
        """
        pass


class RetryablePlugin(Plugin):
    """
    Plugin adding support for file which keeps track
    of files which are pending completion.
    """
    
    stop_retry_on_error = False
    cache = None
    queue = []

    def registered(self):
        self.load_queue()
        try:
            if self.queue:
                _log.debug("Attempting to reprocess failed files.")
            for sn, format, file in list(self.queue):
                if self.data_availible(sn, format, [file], is_retry=True):
                    self.queue.remove((sn, format, file))
                elif self.stop_retry_on_error:
                    break
        finally:
            self.sync_queue()

    def sync_queue(self):
        if self.cache:
            with open(self.cache, "w") as file:
                file.writelines("%d,%s,%s\n" % e for e in self.queue)
    
    def load_queue(self):
        if self.cache and os.path.isfile(self.cache):
            with open(self.cache, "r") as file:
                lines = file.read().splitlines()
            self.queue = []
            for line in lines:
                device_sn, format, file = line.split(",")
                if os.path.isfile(file):
                    self.queue.append((int(device_sn), format, file))
                else:
                    _log.warning("File queued by plugin disappeared. %s", file)

    def add_to_queue(self, device_sn, format, files):
        for file in files:
            self.queue.append((device_sn, format, file))


def register_plugins(*plugins):
    _plugins.extend(p for p in plugins if p is not None)
    for plugin in plugins:
        try: plugin and plugin.registered()
        except Exception: _log.warning("Plugin failed. %s", plugin, exc_info=True)

def publish_data(device_sn, format, files):
    for plugin in _plugins:
        try: plugin.data_availible(device_sn, format, files)
        except Exception: _log.warning("Plugin failed. %s", plugin, exc_info=True)


# vim: ts=4 sts=4 et
